language: java
jdk:
- oraclejdk8
script:
- gradle build
before_deploy:
- ls -R
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: fDCZL1sE4D1rmipjiGlAmwUdnmGtL8mN7tao/uEouwl8J4khDmgfDNKqE4s1rM2OyEIoyRbU/zvzXFJMFQBoWr9T2L4Xc4kchvwuyVqop8BhuenEQihyvS/Jpvpemjv73MztdrVYIX+05RrCpLCv6UPt1TEsURTeSobg4/a4Gv7kPxuR6sypvTomdOmJ1YGzbTtMT85BPTUVTjUP3vP3QSl2kTadF4qD9Y2wcPZT1e3SV/TC9sNDQ7RfRxPNMOJeneeZ5MaXDIxav1tXvEwJT2gIzohjvFPhsiOw1AxaB3aPv0fJVqLBL+D6L7UNDWh9WPbwVEu3LqPpnOKnwNHy34vnEeaCNmJHTeCKUMEhz3ml0qnAlJEvXXCG02VrYu0+pfo22z4Jf/Kmv1LGbQP9N5P3Ismi9od/MBM9q82Qv4V9nB+q5P/K5wvXGd/xKRkn8jUubzRC00LgXhIkcPqZjNEGZDr4bMBmkYReQBXv8XspWIZlqmlkh+4Q+UokfF0AKb9XGSVBaDC3voV/aQcrV7rAkeIz2pZJwTmg74pFVGqu5K6YuSf2JZ3HawWdSvFrT6+nQ3MB3lU74YiwnH2FEV1gOABG2N3FimlQo94EAQbji2J1UQBrbq5iU0lAUaQZtzXBLnMUPjIRHM0pasRYpJg9qp3LE3Zba0cNyLpWD18=
  file: build/libs/psql-multi-all.jar
  on:
    tags: true
    all_branches: true
